DEVICE_PATH := device/xiaomi/dash

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_SUPPORTS_64_BIT_APPS := true

TARGET_OTA_ASSERT_DEVICE := dash
TARGET_BOARD_PLATFORM := mt6991
TARGET_BOOTLOADER_BOARD_NAME := mt6991
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_NO_KERNEL := true
TARGET_NO_RECOVERY := true
BOARD_USES_MTK_HARDWARE := true

BOARD_BOOT_HEADER_VERSION := 4
BOARD_VENDOR_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_PAGESIZE := 4096
BOARD_PAGE_SIZE := 4096
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_USERIMAGES_USE_EROFS := true
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_USES_METADATA_PARTITION := true
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/system/etc/recovery.fstab

TW_THEME := portrait_hdpi
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
TW_MAX_BRIGHTNESS := 16383
TW_DEFAULT_BRIGHTNESS := 1000

OF_STATUS_H := 112
OF_STATUS_INDENT_LEFT := 80
OF_STATUS_INDENT_RIGHT := 60
OF_CLOCK_POS := 1
OF_FLASHLIGHT_ENABLE := 1
OF_FL_PATH1 := /sys/class/leds/white:flash-1
OF_FL_PATH2 := /sys/class/leds/white:flash-2

TW_INCLUDE_FASTBOOTD := true
TW_INCLUDE_LPTOOLS := true
TW_INCLUDE_LPDUMP := true
TW_INCLUDE_REPACKTOOLS := true
OF_NO_REFLASH_CURRENT_ORANGEFOX := 1
FOX_DISABLE_UPDATEZIP := 1
FOX_DELETE_MAGISK_ADDON := 1
FOX_EXCLUDE_NANO_EDITOR := 1
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_EROFS := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_USE_LEGACY_BATTERY_SERVICES := true
TW_DEFAULT_LANGUAGE := en
RECOVERY_SDCARD_ON_DATA := true
TW_HAS_MTP := true
TW_MTP_DEVICE := /dev/mtp_usb
TW_NO_USB_STORAGE := true
TARGET_USES_LOGD := true
TWRP_INCLUDE_LOGCAT := true

TW_INCLUDE_CRYPTO := true
TW_INCLUDE_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
TW_USE_FSCRYPT_POLICY := 2
VENDOR_SECURITY_PATCH := 2026-08-01

TW_LOAD_VENDOR_MODULES := nxp_i2c.ko\ p73.ko\ mtk-composite.ko\ flashlight.ko\ leds-mt6379.ko\ leds-mt6379pmic.ko\ xiaomi_spi_tee.ko\ mtk_ioctl_touch_boost.ko\ touch_boost.ko\ xiaomi_touch_dash.ko\ nt38771_touch_dash.ko\ fs3002_haptic.ko
TW_LOAD_VENDOR_BOOT_MODULES := true
TW_LOAD_VENDOR_MODULES_KEEP_ODM := true

BOARD_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/vendor

OF_MAINTAINER := Raka Rizaldy

OF_MANUAL_ROOT_VENDOR_ERROR_FIX := 1

TW_DEFER_DATA_DECRYPT := true

BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true

TW_RECOVERY_ADDITIONAL_RELINK_LIBRARY_FILES += \
    $(TARGET_OUT_SHARED_LIBRARIES)/libkeymaster_messages.so \
    $(TARGET_OUT_SHARED_LIBRARIES)/android.hardware.security.rkp-V3-ndk.so \
    $(TARGET_OUT_SHARED_LIBRARIES)/android.hardware.security.secureclock-V1-ndk.so \
    $(TARGET_OUT_SHARED_LIBRARIES)/android.hardware.security.sharedsecret-V1-ndk.so \
    $(TARGET_OUT_SHARED_LIBRARIES)/android.hardware.weaver-V1-ndk_platform.so
