DEVICE_PATH := device/xiaomi/dash

ALLOW_MISSING_DEPENDENCIES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_SUPPORTS_64_BIT_APPS := true

TARGET_OTA_ASSERT_DEVICE := dash
TARGET_BOARD_PLATFORM := mt6991
TARGET_BOOTLOADER_BOARD_NAME := mt6991
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_NO_KERNEL := true
TARGET_NO_RECOVERY := true
BOARD_USES_MTK_HARDWARE := true

TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
BOARD_USES_GENERIC_KERNEL_IMAGE := true
BOARD_EXCLUDE_KERNEL_FROM_RECOVERY_IMAGE := true
BOARD_BOOT_HEADER_VERSION := 4
BOARD_VENDOR_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_PAGESIZE := 4096
BOARD_PAGE_SIZE := 4096
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_PREBUILT_DTBIMAGE_DIR := $(DEVICE_PATH)/prebuilt/stock/dtb
BOARD_RAMDISK_USE_LZ4 := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true

BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_INIT_BOOT_IMAGE_PARTITION_SIZE := 8388608
BOARD_DTBOIMG_PARTITION_SIZE := 8388608
BOARD_SUPER_PARTITION_SIZE := 12884901888

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_USERIMAGES_USE_EROFS := true
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_USES_METADATA_PARTITION := true
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/system/etc/recovery.fstab

TW_THEME := portrait_hdpi
TARGET_SCREEN_WIDTH := 1280
TARGET_SCREEN_HEIGHT := 2772
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
TW_MAX_BRIGHTNESS := 16383
TW_DEFAULT_BRIGHTNESS := 1000

# DASH MT6379 camera torch exposed through the native OrangeFox flashlight backend.
OF_FLASHLIGHT_ENABLE := 1
OF_FL_PATH1 := /sys/class/leds/white:flash-1
OF_FL_PATH2 := /sys/class/leds/white:flash-2

TW_INCLUDE_FASTBOOTD := true
TW_INCLUDE_LPTOOLS := true
TW_INCLUDE_LPDUMP := true
TW_INCLUDE_REPACKTOOLS := true
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_EROFS := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_USE_LEGACY_BATTERY_SERVICES := true
TW_DEFAULT_LANGUAGE := en
RECOVERY_SDCARD_ON_DATA := true
TW_HAS_MTP := true
TW_MTP_DEVICE := /dev/mtp_usb
TW_NO_USB_STORAGE := true
TARGET_USES_LOGD := true
TWRP_INCLUDE_LOGCAT := true

TW_INCLUDE_CRYPTO := true
TW_INCLUDE_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
TW_USE_FSCRYPT_POLICY := 2

# Stock ID303 vendor SPL used by recovery prop.default / MiTEE KeyMint.
VENDOR_SECURITY_PATCH := 2026-08-01

BOARD_AVB_ENABLE := true

# OrangeFox 14.1: preserve physical recovery /vendor payload during ramdisk assembly.
OF_MANUAL_ROOT_VENDOR_ERROR_FIX := 1

# DASH stock vendor_dlkm touch chain. OrangeFox resolves dependencies via stock modules.dep.
TW_LOAD_VENDOR_MODULES := usb_offload.ko\ mtk-composite.ko\ flashlight.ko\ leds-mt6379.ko\ leds-mt6379pmic.ko\ xiaomi_spi_tee.ko\ mtk_ioctl_touch_boost.ko\ touch_boost.ko\ xiaomi_touch_dash.ko\ nt38771_touch_dash.ko\ fs3002_haptic.ko
TW_LOAD_VENDOR_MODULES_EXCLUDE_GKI := true

# DASH recovery device-node labels required by stock BootControl HAL.
BOARD_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/vendor

# OrangeFox release identity
OF_MAINTAINER := Raka Rizaldy
