DEVICE_PATH := device/xiaomi/dash

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_SUPPORTS_64_BIT_APPS := true

TARGET_OTA_ASSERT_DEVICE := dash
TARGET_BOARD_PLATFORM := mt6991
TARGET_BOOTLOADER_BOARD_NAME := mt6991
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_NO_KERNEL := true
TARGET_NO_RECOVERY := true
BOARD_USES_MTK_HARDWARE := true

TARGET_COPY_OUT_VENDOR := vendor

BOARD_BOOT_HEADER_VERSION := 4
BOARD_VENDOR_BOOT_HEADER_VERSION := 4
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_PREBUILT_DTBIMAGE_DIR := $(DEVICE_PATH)/prebuilt/dtb
BOARD_KERNEL_PAGESIZE := 4096
BOARD_PAGE_SIZE := 4096
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864

ifeq ($(FOX_VENDOR_BOOT_RECOVERY),1)
BOARD_USES_RECOVERY_AS_BOOT :=
BOARD_EXCLUDE_KERNEL_FROM_RECOVERY_IMAGE :=
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_USES_GENERIC_KERNEL_IMAGE := true
BOARD_MOVE_GSI_AVB_KEYS_TO_VENDOR_BOOT := true

ifeq ($(BOARD_BOOT_HEADER_VERSION),4)
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
endif
endif

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_USERIMAGES_USE_EROFS := true
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_USES_METADATA_PARTITION := true
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/system/etc/recovery.fstab

TW_THEME := portrait_hdpi
OF_SCREEN_H := 2339
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TW_BRIGHTNESS_PATH := "/sys/devices/platform/mtk-leds/leds/lcd-backlight/brightness"
TW_MAX_BRIGHTNESS := 16383
TW_DEFAULT_BRIGHTNESS := 1638

OF_STATUS_H := 112
OF_STATUS_INDENT_LEFT := 80
OF_STATUS_INDENT_RIGHT := 60
OF_CLOCK_POS := 1
OF_FLASHLIGHT_ENABLE := 1
OF_FL_PATH1 := /sys/class/leds/white:flash-1
OF_FL_PATH2 := /sys/class/leds/white:flash-2

TW_INCLUDE_FASTBOOTD := true
OF_USE_AIDL_BOOT_CONTROL := 1
TW_INCLUDE_LPTOOLS := true
TW_INCLUDE_LPDUMP := true
OF_ENABLE_ALL_PARTITION_TOOLS := 1
OF_ENABLE_FRP_ADDON := 1
TW_DASH_MANUAL_REFLASH_CURRENT_DEFAULT := true
TW_INCLUDE_NTFS_3G := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_DEFAULT_LANGUAGE := en

FOX_SETTINGS_ROOT_DIRECTORY := /persist
FOX_MISCELLANEOUS_ROOT_DIRECTORY := /sdcard
FOX_ALLOW_EARLY_SETTINGS_LOAD := 1
FOX_DASH_PERSIST_SPLASH := 1
RECOVERY_SDCARD_ON_DATA := true
TW_MTP_DEVICE := /dev/mtp_usb
TARGET_USES_LOGD := true
TWRP_INCLUDE_LOGCAT := true

TW_INCLUDE_CRYPTO := true
TW_INCLUDE_OMAPI := true
TW_INCLUDE_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
TW_USE_FSCRYPT_POLICY := 2
VENDOR_SECURITY_PATCH := 2099-12-31
TW_SKIP_KEYMASTER_VERSION_DETECT := true

TW_LOAD_VENDOR_MODULES := fs3002_haptic.ko\ xiaomi_spi_tee.ko\ xiaomi_touch_dash.ko\ nt38771_touch_dash.ko
TW_LOAD_VENDOR_MODULES_DEFERRED := mtk_ioctl_touch_boost.ko\ touch_boost.ko\ mtk-composite.ko\ flashlight.ko\ leds-mt6379.ko\ leds-mt6379pmic.ko
TW_LOAD_VENDOR_MODULES_SELECTIVE_COPY := true
TW_LOAD_VENDOR_BOOT_MODULES := true
TW_LOAD_VENDOR_MODULES_KEEP_ODM := true

TW_SKIP_ADDITIONAL_FSTAB := true

BOARD_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/vendor

OF_MAINTAINER := Raka Rizaldy


BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true

TW_RECOVERY_ADDITIONAL_RELINK_LIBRARY_FILES += \
    $(TARGET_OUT_SHARED_LIBRARIES)/libkeymaster_messages.so \
    $(TARGET_OUT_SHARED_LIBRARIES)/android.hardware.security.rkp-V3-ndk.so \
    $(TARGET_OUT_SHARED_LIBRARIES)/android.hardware.security.secureclock-V1-ndk.so \
    $(TARGET_OUT_SHARED_LIBRARIES)/android.hardware.security.sharedsecret-V1-ndk.so \
    $(TARGET_OUT_SHARED_LIBRARIES)/android.hardware.weaver-V1-ndk_platform.so
