#!/usr/bin/env bash
export FOX_SETTINGS_ROOT_DIRECTORY=/persist
export FOX_MISCELLANEOUS_ROOT_DIRECTORY=/sdcard
export FOX_ALLOW_EARLY_SETTINGS_LOAD=1
export FOX_DASH_PERSIST_SPLASH=1
export FOX_ADD_API_V36_PREBUILTS=2
